In [ ]:
# !pip install eunjeon # 윈도우에선 이거깔면됨

  Using cached https://files.pythonhosted.org/packages/68/90/3232725f974abf6d38f1e2cfd7a6b958337133b3fdc5b3e8994e03d7c2d3/eunjeon-0.4.0.tar.gz
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.


In [ ]:
!pip install konlpy

     |████████████████████████████████| 19.4MB 1.3MB/s 
     |████████████████████████████████| 92kB 8.5MB/s 
     |████████████████████████████████| 3.8MB 42.1MB/s 
  Found existing installation: beautifulsoup4 4.6.3
    Uninstalling beautifulsoup4-4.6.3:
      Successfully uninstalled beautifulsoup4-4.6.3
  Found existing installation: tweepy 3.6.0
    Uninstalling tweepy-3.6.0:
      Successfully uninstalled tweepy-3.6.0


In [ ]:
# !apt-get install openjdk-8-jdk-headless -qq > /dev/null
# !pip3 install JPype1-py3

In [ ]:
# import os
# os.chdir('/tmp/')
# !curl -LO https://bitbucket.org/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.1.tar.gz
# !tar zxfv mecab-0.996-ko-0.9.1.tar.gz
# os.chdir('/tmp/mecab-0.996-ko-0.9.1')
# !./configure
# !make
# !make check
# !make install

In [ ]:
!apt-get update
!apt-get install g++ openjdk-8-jdk 
!pip3 install konlpy JPype1-py3
!bash <(curl -s https://raw.githubusercontent.com/konlpy/konlpy/master/scripts/mecab.sh)

Get:1 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/ InRelease [3,626 B]
Ign:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Hit:3 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:4 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease [21.3 kB]
Get:5 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Ign:6 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Hit:7 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release
Hit:8 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
Get:9 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:10 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/ Packages [95.7 kB]
Get:11 http://ppa.launchpad.net/marutter/c2d4u3.5/ubuntu bionic InRelease [15.4 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic-backports InRelea

# 모듈 설치완료 이후 프로그램 짬

In [22]:
from google.colab import files
uploaded = files.upload()

KeyboardInterrupt: ignored

In [ ]:
import tensorflow as tf
tf.__version__

'2.3.0'

In [81]:
from tensorflow.python import keras
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense, LSTM, Embedding,Dropout,GlobalMaxPool1D
from tensorflow.python.keras.preprocessing import sequence
from tensorflow.python.keras.preprocessing.text import Tokenizer
from tensorflow.python.keras.utils import np_utils
import tensorflow as tf
#from eunjeon import Mecab
from konlpy.tag import Mecab
import pandas as pd
import os

In [90]:
data= pd.read_csv('/content/juicy1.csv')

# 카테고리 숫자로 변경

In [91]:
category=["경제","국제","문화","사회","스포츠","취미","연예","정치","IT&과학","라이프"]

idx=0
for i in data["카테고리"]:
    #print(i)
    if i == category[0]:
        data['카테고리'][idx]=0
    elif i == category[1]:
        data['카테고리'][idx]=1
    elif i == category[2]:
        data['카테고리'][idx]=2
    elif i == category[3]:
        data['카테고리'][idx]=3
    elif i == category[4]:
        data['카테고리'][idx]=4
    elif i == category[5]:
        data['카테고리'][idx]=5
    elif i == category[6]:
        data['카테고리'][idx]=6
    elif i == category[7]:
        data['카테고리'][idx]=7
    elif i == category[8]:
        data['카테고리'][idx]=8
    elif i == category[9]:
        data['카테고리'][idx]=9
    idx+=1
    

In [79]:
#del data["내용"][56936]
#del data["카테고리"][56935]

In [89]:
import math
if math.isnan(data["내용"][67051]) :
  print("a")
#len(set(data["카테고리"].iloc[:].values))

a


## 형태소 분류

In [93]:
import math

mecab=Mecab()

tag_classes=['NNG','NNP','VA','VV+EC','XSV+EP','XSV+EF','XSV+EC','VV+ETM']
i=0

while i<len(data["내용"]):
    # if(i==56935):
    #   i+=1
    #   continue
    # if(i==67051):
    #   i+=1
    #   continue    
    speech=data["내용"][i]
    try:
      speech_pos = mecab.pos(speech)
    except:
      print(i)
      i+=1
      continue
    
    if i%5000==0:
      print(i)
    data["내용"][i]=[n for n, tag in speech_pos if tag in tag_classes ]
    
    i+=1

0
5000
10000
15000
20000
25000
30000
35000
40000
45000
50000
55000
56935
60000
65000
67051
70000
75000
80000
85000
90000


# 데이터 전처리

In [112]:
X = data["내용"].iloc[:].values
Y = data["카테고리"].iloc[:].values


In [113]:
import numpy as np

X=np.delete(X,67051)
X=np.delete(X,56935)

Y=np.delete(Y,67051)
Y=np.delete(Y,56935)


In [114]:

Y_classes=len(set(Y))
print(Y_classes)
Y = np_utils.to_categorical(Y,Y_classes)
print(Y)


10
[[1. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]]


In [115]:
idx=0
for i in X:
  if type(i) != list:
    print(idx)
  idx+=1

In [116]:
max_word=5000 #많이 사용된 단어 몇개쓸지
max_len=500 #길이제한(뉴스마다 길이가 다르니 고정 빈부분은 0으로 채움)



tok=Tokenizer(num_words=max_word)
tok.fit_on_texts(X)#각 단어에 번호를 부여
#print(len(tok.word_index))
#print(tok.word_index)

sequences =tok.texts_to_sequences(X)#부여한 번호로 시퀀스화시킴
#print(len(sequences[0]))
#print(sequences[0])

sequences_matrix = sequence.pad_sequences(sequences,maxlen=max_len)#벡터화
# print(sequences_matrix)
# print(sequences_matrix[0])
# print(len(sequences_matrix[0]))

In [117]:

x_train = sequences_matrix[:85000]
x_test = sequences_matrix[85000:]
y_train = Y[:85000]
y_test  = Y[85000:]

print(x_train.shape)
print(y_train.shape)


(85000, 500)
(85000, 10)


# 모델 생성

In [118]:
from keras.callbacks import ModelCheckpoint
from keras.callbacks import EarlyStopping

model = Sequential()

model.add(Embedding(max_word, 120, input_length=max_len))
model.add(LSTM(120))
# model.add(Dense(50, activation='relu'))
# model.add(Dropout(0.5))
model.add(Dense(Y_classes, activation='softmax'))

model.compile(loss='categorical_crossentropy', 
              optimizer='adam', 
              metrics=['accuracy'])

# model_dir='./model'
# if not os.path.exists(model_dir):
#     os.mkdir(model_dir)
# model_path = model_dir+"/juicy.model"
# checkpoint = ModelCheckpoint(filepath=model_path, monitor="val_loss", verbose=1, save_best_only=True)
# early_stopping = EarlyStopping(monitor='val_loss', patience=7)

#정확도가 이전보다 좋아지면 모델 저장
checkpoint= ModelCheckpoint('best_model.h5', monitor='val_accuracy', mode='max', 
                            verbose=1, save_best_only=True)

#손실률 증가 2번하면 멈춤
early_stopping= EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=3)

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 500, 120)          600000    
_________________________________________________________________
lstm (LSTM)                  (None, 120)               115680    
_________________________________________________________________
dense (Dense)                (None, 10)                1210      
Total params: 716,890
Trainable params: 716,890
Non-trainable params: 0
_________________________________________________________________


In [119]:

model.fit(x_train, y_train,
          epochs=60,batch_size=500,
          validation_split=0.2,
          callbacks=[checkpoint,early_stopping]
          )


Epoch 1/60
136/136 [==============================] - ETA: 0s - loss: 1.0740 - accuracy: 0.6434
Epoch 00001: val_accuracy improved from -inf to 0.79071, saving model to best_model.h5
136/136 [==============================] - 161s 1s/step - loss: 1.0740 - accuracy: 0.6434 - val_loss: 0.6361 - val_accuracy: 0.7907
Epoch 2/60
136/136 [==============================] - ETA: 0s - loss: 0.5462 - accuracy: 0.8185
Epoch 00002: val_accuracy improved from 0.79071 to 0.83459, saving model to best_model.h5
136/136 [==============================] - 161s 1s/step - loss: 0.5462 - accuracy: 0.8185 - val_loss: 0.5281 - val_accuracy: 0.8346
Epoch 3/60
136/136 [==============================] - ETA: 0s - loss: 0.4378 - accuracy: 0.8615
Epoch 00003: val_accuracy improved from 0.83459 to 0.84982, saving model to best_model.h5
136/136 [==============================] - 160s 1s/step - loss: 0.4378 - accuracy: 0.8615 - val_loss: 0.4815 - val_accuracy: 0.8498
Epoch 4/60
136/136 [=============================

In [127]:
from tensorflow.keras.models import load_model

loaded_model = load_model('best_model.h5')
print("\n 테스트 정확도: %.4f" % (loaded_model.evaluate(x_test, y_test)[1]))

184/184 [==============================] - 40s 218ms/step - loss: 0.4143 - accuracy: 0.8702

 테스트 정확도: 0.8702


# 테스트 데이터 확인

In [ ]:
from tensorflow.keras.models import load_model
loaded_model = load_model('best_model.h5')

answer=loaded_model.predict_classes(x_test)
test_data= pd.read_csv('/content/juicy1.csv')

In [128]:
question_num=100
question=test_data["내용"][85000+question_num]
question_answer=test_data["카테고리"][85000+question_num]

print(question+"\n----------------------------------")
print("도출값: "+category[answer[question_num]])
print("정답: "+question_answer)



     불법 경영승계 혐의 등을 받는 이재용 삼성전자 부회장이 9일 오전 구속영장이 기각되자 경기 의왕시 서울구치소를 나서고 있다. [뉴시스]         구속을 면한 이재용(52) 삼성전자 부회장 측이 검찰에 요청한 수사심의위원회는 2년 6개월이란 짧은 역사에 비해 중요 사건의 길목에서 핵심적인 역할을 해왔다.         20만쪽 수사기록 0.0015%로 압축한 30쪽 의견서가 핵심    2018년 강원랜드 채용비리 수사팀이 수사외압 혐의로 현직 검사장들을 기소하려할 때도 요청됐다. 같은 해 불법파업 혐의를 받았던 기아차 노조원들의 불기소 결정도 수사심의위원회 권고 때문이었다. 2019년엔 수사심위원회가 3년 6개월째 복직 투쟁을 벌였던 아사히글라스 노동자들의 손을 들어주며 원청업체 기소를 권고하기도 했다.            20만쪽 수사기록 중 0.0015% 추려내야     문무일 전 검찰총장이 2017년 "검찰 수사의 투명성을 확대하겠다"며 검찰 개혁의 일환으로 만든 수사심의위원회가 이 부회장 측의 요청으로 또다시 관심을 끌고 있다. 사건 관계자가 요구할 시 각계 전문가로 구성된 수사심의위원회의 권고에 따라 검찰이 기소 여부를 결정토록 하는 이 제도에 대한 이 부회장 측과 검찰 수사팀의 의견은 엇갈린다.            양측은 당장 이 사건의 수사심의위원회 채택 여부를 결정할 11일 부의위원회에 'A4용지 30쪽 이내' 의견서를 제출해야 한다. 20만쪽의 수사기록 중 0.0015%의 알맹이만 추려내 위원들을 설득해야 한다는 것이다. 부의위원회에선 본 심의위원회와 달리 의견서 외 구술 변론은 허용되지 않는다.               강원랜드 채용비리 수사 관련한 외압 의혹을 폭로했던 안미현 검사가 2018년 5월 15일 서초구 교육문화관에서 기자회견을 열고 수사 상황에 대한 입장을 발표하고 있다. [뉴스1]    강원랜드 항명사태 사례       앞선 수사심의위원회 사례 중 언론의 가장 많은 주목을 받았던 사건은 2018년 강원랜드 채용비리

In [124]:
answer=loaded_model.predict_classes(x_test)
answer#학습된 모델에서 도출된 결과

array([0, 3, 0, ..., 1, 2, 4])

In [126]:
data["카테고리"].iloc[2000:].values#기존 정답

array([2, 3, 0, ..., 1, 9, 4], dtype=object)