In [ ]:
# !pip install eunjeon # 윈도우에선 이거깔면됨

  Using cached https://files.pythonhosted.org/packages/68/90/3232725f974abf6d38f1e2cfd7a6b958337133b3fdc5b3e8994e03d7c2d3/eunjeon-0.4.0.tar.gz
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.


In [1]:
!pip install konlpy

     |████████████████████████████████| 19.4MB 68.7MB/s 
     |████████████████████████████████| 3.8MB 50.3MB/s 
     |████████████████████████████████| 92kB 10.6MB/s 
  Found existing installation: beautifulsoup4 4.6.3
    Uninstalling beautifulsoup4-4.6.3:
      Successfully uninstalled beautifulsoup4-4.6.3
  Found existing installation: tweepy 3.6.0
    Uninstalling tweepy-3.6.0:
      Successfully uninstalled tweepy-3.6.0


In [2]:
# !apt-get install openjdk-8-jdk-headless -qq > /dev/null
# !pip3 install JPype1-py3

In [3]:
# import os
# os.chdir('/tmp/')
# !curl -LO https://bitbucket.org/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.1.tar.gz
# !tar zxfv mecab-0.996-ko-0.9.1.tar.gz
# os.chdir('/tmp/mecab-0.996-ko-0.9.1')
# !./configure
# !make
# !make check
# !make install

In [4]:
!apt-get update
!apt-get install g++ openjdk-8-jdk 
!pip3 install konlpy JPype1-py3
!bash <(curl -s https://raw.githubusercontent.com/konlpy/konlpy/master/scripts/mecab.sh)

Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease [21.3 kB]
Get:4 http://ppa.launchpad.net/marutter/c2d4u3.5/ubuntu bionic InRelease [15.4 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:6 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/ InRelease [3,626 B]
Get:7 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Ign:8 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Ign:9 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Hit:10 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release
Hit:11 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
Get:12 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Pac

# 모듈 설치완료 이후 프로그램 짬

In [6]:
from google.colab import files
uploaded = files.upload()

Saving juicy.csv to juicy.csv


In [7]:
import tensorflow as tf
tf.__version__

'2.3.0'

In [8]:
from tensorflow.python import keras
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense, LSTM, Embedding,Dropout,GlobalMaxPool1D
from tensorflow.python.keras.preprocessing import sequence
from tensorflow.python.keras.preprocessing.text import Tokenizer
from tensorflow.python.keras.utils import np_utils
import tensorflow as tf
#from eunjeon import Mecab
from konlpy.tag import Mecab
import pandas as pd
import os

In [9]:
data= pd.read_csv('/content/juicy.csv')

# 카테고리 숫자로 변경

In [10]:
category=["Mr.밀리터리", "더,오래", "중앙SUNDAY", "강갑생의 바퀴와 날개", "경제",
          "국제", "그게머니", "독자 서비스","라이프 스타일", "리셋 코리아", 
          "문화", "백성호의 현문우답", "사회", "스포츠", "안장원의 부동산 노트", 
          "알지RG", "애니띵", "여행레저", "연예", "오피니언", "윤석만의 인간혁명",
          "이철재의 밀담", "정치", "채인택의 글로벌 줌업", "폴인 인사이트", "피플"]

idx=0
for i in data["category"]:
    #print(i)
    if i == "\n\nMr.밀리터리\n":
        data['category'][idx]=0
    elif i=='\n\n더,오래\n':
        data['category'][idx]=1
    elif i=='\n\n중앙SUNDAY\n':
        data['category'][idx]=2
    elif i=='강갑생의 바퀴와 날개':
        data['category'][idx]=3
    elif i=='경제':
        data['category'][idx]=4
    elif i=='국제':
        data['category'][idx]=5
    elif i=='그게머니':
        data['category'][idx]=6
    elif i=='독자 서비스':
        data['category'][idx]=7
    elif i=='라이프 스타일':
        data['category'][idx]=8
    elif i=='리셋 코리아':
        data['category'][idx]=9
    elif i=='문화':
        data['category'][idx]=10
    elif i=='백성호의 현문우답':
        data['category'][idx]=11
    elif i=='사회':
        data['category'][idx]=12
    elif i=='스포츠':
        data['category'][idx]=13
    elif i=='안장원의 부동산 노트':
        data['category'][idx]=14
    elif i=='알지RG':
        data['category'][idx]=15
    elif i=='애니띵':
        data['category'][idx]=16
    elif i=='여행레저':
        data['category'][idx]=17
    elif i=='연예':
        data['category'][idx]=18
    elif i=='오피니언':
        data['category'][idx]=19
    elif i=='윤석만의 인간혁명':
        data['category'][idx]=20
    elif i=='이철재의 밀담':
        data['category'][idx]=21
    elif i=='정치':
        data['category'][idx]=22
    elif i=='채인택의 글로벌 줌업':
        data['category'][idx]=23
    elif i=='폴인 인사이트':
        data['category'][idx]=24
    elif i=='피플':
        data['category'][idx]=25
    idx+=1
    

## 형태소 분류

In [11]:
mecab=Mecab()

tag_classes=['NNG','NNP','VA','VV+EC','XSV+EP','XSV+EF','XSV+EC','VV+ETM']
i=0

while i<len(data["content"]):
    speech=data["content"][i]
    speech_pos = mecab.pos(speech)

    data["content"][i]=[n for n, tag in speech_pos if tag in tag_classes ]
    
    i+=1

# 데이터 전처리

In [12]:
X = data["content"].iloc[:].values
Y = data["category"].iloc[:].values

Y_classes=len(set(Y))
print(Y_classes)
Y = np_utils.to_categorical(Y,Y_classes)
print(Y)


26
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [13]:
max_word=5000 #많이 사용된 단어 몇개쓸지
max_len=500 #길이제한(뉴스마다 길이가 다르니 고정 빈부분은 0으로 채움)



tok=Tokenizer(num_words=max_word)
tok.fit_on_texts(X)#각 단어에 번호를 부여
#print(len(tok.word_index))
#print(tok.word_index)

sequences =tok.texts_to_sequences(X)#부여한 번호로 시퀀스화시킴
#print(len(sequences[0]))
#print(sequences[0])

sequences_matrix = sequence.pad_sequences(sequences,maxlen=max_len)#벡터화
# print(sequences_matrix)
# print(sequences_matrix[0])
# print(len(sequences_matrix[0]))

In [14]:

x_train = sequences_matrix[:2000]
x_test = sequences_matrix[2000:]
y_train = Y[:2000]
y_test  = Y[2000:]

print(x_train.shape)
print(y_train.shape)


(2000, 500)
(2000, 26)


# 모델 생성

In [15]:
from keras.callbacks import ModelCheckpoint
from keras.callbacks import EarlyStopping

model = Sequential()

model.add(Embedding(max_word, 120, input_length=max_len))
model.add(LSTM(120))
# model.add(Dense(50, activation='relu'))
# model.add(Dropout(0.5))
model.add(Dense(Y_classes, activation='softmax'))

model.compile(loss='categorical_crossentropy', 
              optimizer='adam', 
              metrics=['accuracy'])

# model_dir='./model'
# if not os.path.exists(model_dir):
#     os.mkdir(model_dir)
# model_path = model_dir+"/juicy.model"
# checkpoint = ModelCheckpoint(filepath=model_path, monitor="val_loss", verbose=1, save_best_only=True)
# early_stopping = EarlyStopping(monitor='val_loss', patience=7)

#정확도가 이전보다 좋아지면 모델 저장
checkpoint= ModelCheckpoint('best_model.h5', monitor='val_accuracy', mode='max', 
                            verbose=1, save_best_only=True)

#손실률 증가 2번하면 멈춤
early_stopping= EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=3)

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 500, 120)          600000    
_________________________________________________________________
lstm (LSTM)                  (None, 120)               115680    
_________________________________________________________________
dense (Dense)                (None, 26)                3146      
Total params: 718,826
Trainable params: 718,826
Non-trainable params: 0
_________________________________________________________________


In [16]:

model.fit(x_train, y_train,
          epochs=50,batch_size=500,
          validation_split=0.2,
          callbacks=[checkpoint,early_stopping]
          )


Epoch 1/50
4/4 [==============================] - ETA: 0s - loss: 3.2449 - accuracy: 0.2650
Epoch 00001: val_accuracy improved from -inf to 0.37250, saving model to best_model.h5
4/4 [==============================] - 6s 1s/step - loss: 3.2449 - accuracy: 0.2650 - val_loss: 3.2151 - val_accuracy: 0.3725
Epoch 2/50
4/4 [==============================] - ETA: 0s - loss: 3.1862 - accuracy: 0.4750
Epoch 00002: val_accuracy did not improve from 0.37250
4/4 [==============================] - 5s 1s/step - loss: 3.1862 - accuracy: 0.4750 - val_loss: 3.1246 - val_accuracy: 0.3725
Epoch 3/50
4/4 [==============================] - ETA: 0s - loss: 3.0120 - accuracy: 0.3931
Epoch 00003: val_accuracy did not improve from 0.37250
4/4 [==============================] - 6s 1s/step - loss: 3.0120 - accuracy: 0.3931 - val_loss: 2.4761 - val_accuracy: 0.2600
Epoch 4/50
4/4 [==============================] - ETA: 0s - loss: 2.2898 - accuracy: 0.2431
Epoch 00004: val_accuracy did not improve from 0.37250
4/

In [17]:
from tensorflow.keras.models import load_model

loaded_model = load_model('best_model.h5')
print("\n 테스트 정확도: %.4f" % (loaded_model.evaluate(x_test, y_test)[1]))

7/7 [==============================] - 1s 130ms/step - loss: 0.9022 - accuracy: 0.7662

 테스트 정확도: 0.7662


# 테스트 데이터 확인

In [18]:
from tensorflow.keras.models import load_model
loaded_model = load_model('best_model.h5')

answer=loaded_model.predict_classes(x_test)
test_data= pd.read_csv('/content/juicy.csv')

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


In [19]:
question_num=100
question=test_data["content"][2000+question_num]
question_answer=test_data["category"][2000+question_num]

print(question+"\n----------------------------------")
print("도출값: "+category[answer[question_num]])
print("정답: "+question_answer)



     18일 동산고와 16강전에서 결승득점을 올린 신일고 오창현. 김효경 기자         신일고가 2년 만에 대통령배 8강에 진출했다. 16강전에서 동산고에 4-3 승리         신일고가 17일 서울 목동야구장에서 열린 제54회 대통령배 전국고교야구대회(중앙일보·일간스포츠·대한야구소프트볼협회 주최) 16강전에서 동산고에 4-3 재역전승을 거뒀다. 2018년 문보경(LG), 김이환(한화)의 활약에 힘입어 4강에 진출했던 신일고는 2년만에 8강에 진출했다.           선제점은 신일고가 올렸다. 1회 말 톱타자 김재두가 좌전안타를 치고 나갔고, 오창현의 희생번트로 만든 1사 2루에서 3번 김휘집이 우전안타로 김재두를 홈으로 불러들였다.           동산고는 4회 초 선두타자 임원묵이 우중간 안타를 치고 나갔다. 그리고 2사 2루에서 정대선이 적시타를 쳤다. 1-1. 동산고는 5회 역전까지 성공했다. 박지훈이 좌익선상 2루타 이후 폭투를 틈타 홈을 밟았다.           동산고는 6회 강제원, 전상혁, 주요한의 안타가 나왔다. 그러나 희생번트 실패와 후속타 불발로 1사 만루에서 득점에 실패했다. 결국 신일고의 반격을 허용했다. 2사 2루에서 오승현이 중견수 방면 2루타를 때려 다시 동점을 만들었다.           7회 동산고가 다시 달아났다. 선두타자 김민우 3루수 실책으로 출루했고, 김용희가 희생번트 1사 2루를 만들었다. 4번 타자 임원묵은 고의볼넷. 이후 투수 임동환이 2개의 폭투를 범하면서 김민우가 득점했다. 그러나 8회 말 다시 균형이 맞춰졌다. 최병용의 내야 안타, 정승구의 희생번트 이후 목지훈이 좌전안타를 때렸다. 3-3.           승부는 9회 말 결정됐다. 선두타자 오창현이 우전 안타를 치고나간 뒤, 김휘집의 좌전안타로 1사 1,3루가 됐다. 권혁경은 고의볼넷으로 1사 만루. 최병용이 친 타구는 우익수 방면으로 날아갔다. 홈으로 파고들던 오창현은 우익수 송구가 날아오자 다시 3루로 돌아갔다. 동산고 포수 임원묵

In [20]:
answer=loaded_model.predict_classes(x_test)
answer#학습된 모델에서 도출된 결과

array([12, 12, 10, 13,  4, 12, 13, 13, 10, 10, 10, 10, 10, 22, 10, 22, 12,
       18, 12, 13,  2, 10, 13, 12, 12,  4,  5, 12, 12, 12,  2, 22, 12, 12,
        4, 12,  4, 12, 10,  4, 12,  4, 10, 10, 22, 10, 10, 10,  4, 10, 10,
       22, 12, 12, 13,  2, 22, 10,  4, 12, 10, 10,  4, 22, 12,  4,  4, 12,
       22, 10, 12, 13, 13, 12,  4, 22, 22, 12, 12, 10, 12, 13, 10,  5, 12,
       12, 12, 10, 10, 12, 22, 12, 12, 10, 22, 10, 12, 12, 22, 10, 13, 22,
        5, 10, 10, 10, 10, 13, 22, 10, 10, 10, 13, 10, 10, 10, 12, 10, 10,
       12, 10, 10, 10, 22, 10, 12, 10, 12, 13, 10, 10, 10, 10, 10, 13, 10,
       10, 10, 10, 13, 10, 12, 10, 10, 10, 13, 10, 12, 12, 22, 12,  2, 10,
        2,  2, 12, 22,  2, 22, 12, 10, 12, 10,  4, 10, 12, 12, 10, 12, 10,
       10, 12, 10, 10, 10, 12, 12, 10, 12, 10,  5,  5, 10, 10, 10, 10, 12,
       12, 12, 10, 22, 12, 12, 12,  4, 12, 22, 12, 12, 22, 12])

In [21]:
data["category"].iloc[2000:].values#기존 정답

array([12, 12, 18, 13, 4, 5, 13, 13, 10, 10, 10, 10, 10, 22, 10, 10, 12,
       10, 13, 13, 1, 12, 13, 13, 12, 12, 5, 12, 12, 4, 23, 22, 13, 4, 22,
       12, 4, 12, 10, 12, 12, 4, 18, 4, 22, 4, 18, 10, 4, 10, 18, 22, 12,
       12, 13, 5, 22, 18, 4, 5, 22, 4, 4, 22, 12, 4, 4, 12, 22, 10, 12,
       13, 13, 12, 4, 22, 22, 12, 12, 18, 12, 13, 18, 22, 12, 12, 22, 18,
       10, 4, 22, 12, 12, 18, 22, 10, 12, 12, 8, 10, 13, 12, 4, 10, 10,
       10, 10, 13, 4, 10, 10, 10, 13, 10, 10, 10, 12, 10, 10, 12, 10, 10,
       10, 4, 10, 12, 10, 12, 13, 10, 10, 10, 10, 10, 13, 10, 10, 10, 10,
       13, 10, 12, 10, 10, 18, 13, 10, 12, 12, 22, 12, 12, 10, 10, 4, 12,
       22, 12, 12, 12, 10, 7, 10, 4, 10, 12, 12, 10, 12, 10, 10, 12, 10,
       10, 10, 12, 5, 10, 10, 10, 5, 5, 10, 10, 4, 10, 12, 12, 12, 10, 22,
       12, 12, 12, 4, 12, 22, 12, 12, 22, 12], dtype=object)